### ISSUE TITLE
10.6.3 library fails unzipping

### ISSUE THREAD

**Issue by josephw** [josephw/titl#20]
Original [issue 20](https://code.google.com/p/titl/issues/detail?id=20) created by josephw on 2012-10-12T15:24:55.000Z:

<b>What steps will reproduce the problem?</b>
1. start with a library of version 10.6.3
2. run one of the routines on it (such as export ratings)
3. get stack trace from java

<b>What is the expected output? What do you see instead?</b>
the proper export rating functionality (i'm not sure what that looks like since i haven't been able to complete it with my library)

<b>What version of the product are you using? On what operating system?</b>
titl-core-0.3-SNAPSHOT.jar

<b>Please provide any additional information below.</b>
I have a project that involves trying to update the date added fields (which are otherwise read-only) to the file timestamps (i started using itunes in 2006 but i'v ehad files as far back as 1996 and would really like to have that data preserved, what songs i've had longest etc)..  So i have been trying to re-implement what titl is doing, but in python. so i can glue the matching/stating of a backup of files.. 

I've gotten so far as doing the parsing of the hdfm properly, but when it's time to decrypt/inflate the rest of the file to get access at the individual hxxx tags, i have been running up into problems trying to get it to decrypt properly.  Now, encryption seems to go smoothly always (and my first byte is 0x78 just like ParseHdfm tells me it should be), but when i tried to inflate using zlib, i get various errors (invalid code lengths is one).  I've tried with just the first 100k decrypted, i tried the entire file decrypted, heck i even tried 16 byte block increments from 0 bytes decrypted to the entire file size.. and nothing will let the inflating complete properly w/o errors!

Sooo... i figure let me just see what titl makes of this since i'm probably coding something wrong.. and lo and behold, titl also has an exception and gives me the following stack trace:

$ java -jar titl-core/target/titl-core-0.3-SNAPSHOT.jar ExportRatings /var/tmp/test.itl
Exception in thread &quot;main&quot; java.lang.reflect.InvocationTargetException
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:39)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:25)
    at java.lang.reflect.Method.invoke(Method.java:597)
    at org.kafsemo.titl.tools.Main.main(Main.java:42)
Caused by: java.util.zip.ZipException: oversubscribed dynamic bit lengths tree
    at java.util.zip.InflaterInputStream.read(InflaterInputStream.java:147)
    at org.kafsemo.titl.Hdfm.inflate(Hdfm.java:221)
    at org.kafsemo.titl.Hdfm.read(Hdfm.java:107)
    at org.kafsemo.titl.ParseLibrary.parse(ParseLibrary.java:90)
    at org.kafsemo.titl.ParseLibrary.parse(ParseLibrary.java:80)
    at org.kafsemo.titl.tools.ExportRatings.main(ExportRatings.java:44)

So i guess titl does not work right on 10.6.3 ? What is the latest version people have had success using titl on?  I've uploaded my titl file in case anyone wnats to duplicate what i'm seeing..

**Comment by NJRoadfan** [comment]
You wouldn't happen to have that python code handy? I have a ton of files with the wrong "date added" on them from moving to a new machine using the XML file method and would like to correct them to the original date added programmatically. I have the .itl library file from the old machine with the original dates.
