### ISSUE TITLE
UnknownHohmException: Unknown type: 517 (0x205)

### ISSUE THREAD

**Issue by LianOrt** [josephw/titl#30]
Hi,
tried your jar on an .itl-file from iTunes 12.1.1.4, 64Bit.
Can you please help ?
Thank you in advance.
Sincerely,
Lian

**Comment by LianOrt** [comment]
Stacktrace is:
org.kafsemo.titl.UnknownHohmException: Unknown type: 517 (0x205)
Hex: 0x00 0x00 0x00 0x00 0x00 0x00 0x00 0x00 0x01 0x01 0x02 0x02 0x02 0x02 0x02 0x02 0x00 0x00 0x00 0x00 0x00 0x00 0x00 0x00
ASCII: ........................
    at org.kafsemo.titl.ParseLibrary.drain(ParseLibrary.java:470)
    at org.kafsemo.titl.ParseLibrary.parse(ParseLibrary.java:94)
    at org.kafsemo.titl.ParseLibrary.parse(ParseLibrary.java:80)

Started from a small JUnit-Test like so:
        Library lib = ParseLibrary.parse(Paths.get("./iTunes Library.itl").toFile());

```
    for (Track t : lib.getTracks()) {
        if(t.getLocation() != null) {
            log.info(t.getLocation() + "," + t.getRating());
        }
    }
```

**Comment by LianOrt** [comment]
Ah excuse me: it's happened on a Win7 64Bit Box
