### ISSUE TITLE
Clarify install instructions

### ISSUE THREAD

**Issue by danvk** [josephw/titl#32]
The Tools page says:

> build a jar then run:
> java -cp itunes.jar org.kafsemo.titl.tools.command

I've tried:

```
git clone https://github.com/josephw/titl.git
cd titl
mvn package
java -cp titl-rdf/target/titl-rdf-0.3-SNAPSHOT.jar org.kafsemo.titl.rdf.LibraryAsRdf
Error: A JNI error has occurred, please check your installation and try again
Exception in thread "main" java.lang.NoClassDefFoundError: org/openrdf/model/URI
```

**Comment by josephw** [comment]
Those instructions will only work for `titl-core`, as `title-rdf` has extra dependencies. Use [`exec-maven-plugin`](http://www.mojohaus.org/exec-maven-plugin/usage.html) or add the libs to the classpath yourself.

**Comment by danvk** [comment]
Thanks, I'll give that a try.

FWIW, I also get an error from the other JAR:

```
$ java -cp titl-core/target/titl-core-0.3-SNAPSHOT.jar org.kafsemo.titl.tools.Main ExportRatings ~/Downloads/iTunes\ Library\ 2009-03-12
Exception in thread "main" java.lang.reflect.InvocationTargetException
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at org.kafsemo.titl.tools.Main.main(Main.java:42)
Caused by: java.io.IOException: Looks complicated...
	at org.kafsemo.titl.ParseLibrary.drain(ParseLibrary.java:159)
	at org.kafsemo.titl.ParseLibrary.parse(ParseLibrary.java:94)
	at org.kafsemo.titl.ParseLibrary.parse(ParseLibrary.java:80)
	at org.kafsemo.titl.tools.ExportRatings.main(ExportRatings.java:44)
	... 5 more
```
